//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentForCourse
    {
        public int studentId { get; set; }
        public int id { get; set; }
        public int courseId { get; set; }
        public string tz { get; set; }
        public string password { get; set; }
    }
}
