//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestForStudent
    {
        public int testId { get; set; }
        public int studentId { get; set; }
        public int mark { get; set; }
        public int id { get; set; }
        public System.DateTime dateStart { get; set; }
    
        public virtual student student { get; set; }
        public virtual Test Test { get; set; }
    }
}
